export const DISH = {
  NEAPOLITANA_PIZZA: 'Neapolitana Pizza',
  BIANKA_PIZZA: 'Bianca Pizza',
  CAPRESE_PIZZA: 'Caprese Pizza',
  QUATTRO_STAGIONI_PIZZA: 'Quattro Stagioni Pizza',
  AL_PESTO_PIZZA: 'Al Pesto Pizza',
  SICILIAN_PIZZA: 'Sicilian Pizza',
  DOLMADES: 'Dolmades',
  MOUSSAKA: 'Moussaka',
  SOUVLAKI: 'Souvlaki',
  SPANAKOPITA: 'Spanakopita',
  BIFTEKI: 'Bifteki',
  PASTITSIO: 'Pastitsio',
  GYROS: 'Gyros',
  KLEFTIKO: 'Kleftiko',
  STIFADO: 'Stifado',
  FAVA: 'Fava',
  EXTRA_CHEESE: 'Extra cheese', 
  MUSHROOM: 'Mushroom', 
  ONION: 'Onion', 
  PEPPERONI: 'Pepperoni', 
  SAUSAGE: 'Sausage', 
  TOMATO: 'Tomato',
  HALLOUMI: 'Halloumi',
  STILL_MINERAL_WATER: 'Still Mineral Water',
  SPARKLINK_MINERAL_WATER: 'Sparkling Mineral Water',
  STRAWBERRY_SMOOTHIE: 'Strawberry Smoothie',
  CARROT_JUICE: 'Carrot Juice',
  PINEAPPLE_JUICE: 'Pineapple Juice',
  ORANGE_JUICE: 'Orange Juice',
  ESPRESSO: 'Espresso',
  CAPPUCCINO: 'Cappuccino',
  LATTE: 'Latte',
  ROOIBOS: 'Rooibos',
  YUNNAN_GREEN_TEA: 'Yunnan Green Tea',
  MAROUVAS_OF_CRETE: 'Marouvas of Crete',
  SHIRAZ_PAARL_SOUTH_AFRICA: 'Shiraz Paarl South Africa',
  RIOJA_SIGLO: 'Rioja Siglo',
  ESTOLA_GRAN_RESERVA_AYUSO: 'Estola Gran Reserva Ayuso',
  CZAJKOWSKI_THOMA_26_MERLOT: 'Czajkowski - Thoma 26 Merlot ',
  OKOCIM_OK_BEER: 'Okocim O.K. Beer',
  BUDWEISER_BUDVAR: 'Budweiser Budvar',
  ZLATY_BAZANT: 'Zlaty Bazant',
  PILSNER_URQUEL_ORIGINAL_PILSNER: 'Pilsner Urquel Original Pilsner',
  GROLSCH_PREMIUM_PILSNER: 'Grolsch Premium Pilsner',
  BELLS_OFFICIAL_HAZY_IPA: 'Bell’s Official Hazy IPA',
  WHALERS_RISE_AMERICAN_PALE_ALE: 'Whalers Rise American Pale Ale',
  SIERRA_NEVADA_PALE_ALE: 'Sierra Nevada Pale Ale',
  SWEET_WATER_420_EXTRA_PALE_ALE: 'Sweet Water 420 Extra Pale Ale'
} as const;
